version: "3.7"

services:
  sql:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - ./Data/sql:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "FakeLock123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1431:1433"
    restart: always

  elasticsearch:
    image: elasticsearch:7.6.0
    volumes:
      - ./Data/elasticSearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
    restart: always

  node:
    image: liorezra73/fakelock_node_server
    volumes:
      - ./logger:/usr/src/logger
      - ./staticFiles/postsPhotos:/usr/src/staticFiles/postsPhotos
    depends_on:
      - sql
      - elasticsearch
    links: 
      - sql
      - elasticsearch
    restart: always
    ports:
      - "3000:3000"

  kibana:
    image: kibana:7.6.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
  angular:
    image: liorezra73/fakelock_angular_client
    depends_on:
      - node
    links: 
      - node
    restart: always
    ports:
      - "4200:4200"
