#run- docker-compose --project-name fakelock up --build
version: "3.7"

services:
  sql:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - ./Data/sql:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "FakeLock123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1431:1433"
    restart: always

  elasticsearch:
    image: elasticsearch:7.6.0
    volumes:
      - ./Data/elasticSearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
    restart: always

  kibana:
    image: kibana:7.6.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always

  # node:
  #   image: liorezra73/fakelock_node_server
  #   volumes:
  #     - /usr/src/node_modules
  #     - .:/usr/src
  #   depends_on:
  #     - sql
  #     - elasticsearch
  #   links:
  #     - sql
  #     - elasticsearch
  #   restart: always
  #   ports:
  #     - "3000:3000"

  node:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/node_modules
      - .:/usr/src
    depends_on:
      - sql
      - elasticsearch
    links:
      - sql
      - elasticsearch
    restart: always
    ports:
      - "3000:3000"

  # angular:
  #   image: liorezra73/fakelock_angular_client
  #   depends_on:
  #     - node
  #   links:
  #     - node
  #   restart: always
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - /usr/src/app/node_modules
  #     - c:\Users\LiorEzra73\Desktop\פרוייקט יהלום\Client\FakeLockClient:/usr/src/app

  angular:
    build: 
      context: c:\Users\LiorEzra73\Desktop\פרוייקט יהלום\Client\FakeLockClient
      dockerfile: Dockerfile.dev
    depends_on:
      - node
    links:
      - node
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - /usr/src/app/node_modules
      - c:\Users\LiorEzra73\Desktop\פרוייקט יהלום\Client\FakeLockClient:/usr/src/app
