version: "3"

services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - c:/Users/LiorEzra73/Desktop/פרוייקט יהלום/Server/Data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "MyPassword12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1431:1433"
    restart: always

  node:
    build: .
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"
